services:
  nginx:
    env_file: .env
    container_name: nginx
    build: requirements/nginx
    depends_on:
      - mariadb
    volumes:
      - www:/var/www/html
    networks:
      - inception
    image: nginx
    ports:
      - 443:443
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - www:/var/www/html
    networks:
      - inception
    build: requirements/wordpress
    image: wordpress
    depends_on:
      - mariadb
    restart: unless-stopped
    ports:
      - 9000:9000 
    secrets:
      - db_password
      - db_root_password
      - credentials

  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: requirements/mariadb
    image: mariadb
    env_file: .env
    volumes:
      - database:/var/lib/mysql
    restart: unless-stopped
    secrets: 
        - db_password
        - db_root_password
        - credentials

volumes:
  www:
    driver: local
    driver_opts:
      type: 'none'
      device: ${VOL_WWW}
      o: 'bind'
  database:
    driver: local
    driver_opts:
      type: 'none'
      device: ${VOL_DB}
      o: 'bind'

networks:
  inception:
    name: inception
    driver: bridge

secrets:
  db_password: 
      file: ../secrets/db_password.txt
  db_root_password: 
      file: ../secrets/db_root_password.txt
  credentials:
      file: ../secrets/credentials.txt